# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod properties
mod.name=Skyboxify
mod.id=skyboxify
mod.version=3.3.1
mod.group=btw.lowercase.skyboxify
mod.description=A skybox mod that allows you to use OptiFine skies in Fabric 1.21+
mod.source=https://github.com/Legacy-Visuals-Project/Skyboxify
mod.issues=https://github.com/Legacy-Visuals-Project/Skyboxify/issues
mod.license=GPL-3.0-with-linking-exception
mod.modrinth=https://modrinth.com/mod/skyboxify
mod.curseforge=https://legacy.curseforge.com/minecraft/mc-mods/skyboxify
mod.discord=https://discord.gg/C8KKgbA8jy

# Publishing
publish.modrinth=DWuwk8aA
publish.curseforge=1301799

# Dependencies
deps.fabric_loader_version=0.18.4
deps.devauth_version=1.2.2
deps.mixinconstraints_version=1.1.0
deps.mixinsquared_version=0.2.0
deps.lombok_version=1.18.42

# Build Plugins
# in libs.versions.toml

# Minecraft properties
mod.mc_version=[VERSIONED]
mod.mc_version_range=[VERSIONED]

# Versioned
deps.parchment_version=[VERSIONED]
deps.fabric_api_version=[VERSIONED]
deps.neoforge_version=[VERSIONED]
